// Demo data for CLOWNPRO - shown when backend is not configured

export const demoEvents = [
  {
    id: 'evt-1',
    tenant_id: 'demo-tenant',
    title: 'Cumpleaños de Sofía - 5 años',
    event_type: 'Cumpleaños',
    event_date: new Date().toISOString().split('T')[0],
    event_time: '14:00',
    duration_minutes: 180,
    address: 'Calle Principal #42, Los Ríos',
    client_id: 'cli-1',
    package_id: null,
    services: ['svc-1', 'svc-2'],
    employees_assigned: ['emp-1'],
    status: 'confirmed',
    total_amount: 7500,
    deposit_amount: 3500,
    notes: 'La niña le encantan los globos y las princesas.',
    clients: { full_name: 'María González', phone: '809-555-0101' },
    event_photos: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-2',
    tenant_id: 'demo-tenant',
    title: 'Baby Shower de Laura',
    event_type: 'Baby shower',
    event_date: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    event_time: '11:00',
    duration_minutes: 120,
    address: 'Salón de Eventos El Dorado, Av. Winston Churchill',
    client_id: 'cli-2',
    package_id: 'pkg-1',
    services: ['svc-3', 'svc-5'],
    employees_assigned: ['emp-2', 'emp-3'],
    status: 'confirmed',
    total_amount: 12500,
    deposit_amount: 5000,
    notes: 'Temática azul y blanco. 30 invitados.',
    clients: { full_name: 'Carmen Rodríguez', phone: '809-555-0102' },
    event_photos: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-3',
    tenant_id: 'demo-tenant',
    title: 'Bautizo del pequeño Carlos',
    event_type: 'Bautizo',
    event_date: new Date(Date.now() + 86400000 * 7).toISOString().split('T')[0],
    event_time: '10:00',
    duration_minutes: 240,
    address: 'Iglesia San José, Zona Colonial',
    client_id: 'cli-3',
    package_id: null,
    services: ['svc-1', 'svc-3', 'svc-4'],
    employees_assigned: ['emp-1', 'emp-4'],
    status: 'quote',
    total_amount: 18500,
    deposit_amount: 0,
    notes: 'Pendiente confirmación del cliente.',
    clients: { full_name: 'Ana Lucía Martínez', phone: '809-555-0103' },
    event_photos: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-4',
    tenant_id: 'demo-tenant',
    title: 'Día del Niño - Escuela Arcoíris',
    event_type: 'Escuela',
    event_date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    event_time: '09:00',
    duration_minutes: 300,
    address: 'Escuela Arcoíris, Calle del Sol #15',
    client_id: 'cli-4',
    package_id: 'pkg-2',
    services: ['svc-1', 'svc-2', 'svc-3', 'svc-4'],
    employees_assigned: ['emp-1', 'emp-2', 'emp-3', 'emp-4'],
    status: 'completed',
    total_amount: 35000,
    deposit_amount: 35000,
    notes: 'Evento para 80 niños. Excelente feedback.',
    clients: { full_name: 'Escuela Arcoíris', phone: '809-555-0104' },
    event_photos: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'evt-5',
    tenant_id: 'demo-tenant',
    title: 'Fiesta Corporativa - Banco Popular',
    event_type: 'Corporativo',
    event_date: new Date(Date.now() + 86400000 * 14).toISOString().split('T')[0],
    event_time: '16:00',
    duration_minutes: 180,
    address: 'Sala de Conferencias Banco Popular, Piantini',
    client_id: 'cli-5',
    package_id: null,
    services: ['svc-2', 'svc-5'],
    employees_assigned: ['emp-2'],
    status: 'confirmed',
    total_amount: 22000,
    deposit_amount: 11000,
    notes: 'Evento para hijos de empleados. 50 niños.',
    clients: { full_name: 'Banco Popular - RRHH', phone: '809-555-0105' },
    event_photos: [],
    created_at: new Date().toISOString(),
  },
]

export const demoClients = [
  { id: 'cli-1', tenant_id: 'demo-tenant', full_name: 'María González', phone: '809-555-0101', email: 'maria.g@email.com', address: 'Calle Principal #42, Los Ríos', notes: 'Cliente frecuente. Prefiere eventos en la mañana.', tags: ['VIP', 'Frecuente'], created_at: new Date().toISOString() },
  { id: 'cli-2', tenant_id: 'demo-tenant', full_name: 'Carmen Rodríguez', phone: '809-555-0102', email: 'carmen.r@email.com', address: 'Av. Independencia #123', notes: 'Recomendó a 3 amigas.', tags: ['Referido'], created_at: new Date().toISOString() },
  { id: 'cli-3', tenant_id: 'demo-tenant', full_name: 'Ana Lucía Martínez', phone: '809-555-0103', email: null, address: 'Urb. Los Prados, Calle 5', notes: 'Pendiente confirmación de bautizo.', tags: ['Cotización'], created_at: new Date().toISOString() },
  { id: 'cli-4', tenant_id: 'demo-tenant', full_name: 'Escuela Arcoíris', phone: '809-555-0104', email: 'directora@arcoiris.edu.do', address: 'Calle del Sol #15', notes: 'Contrata eventos trimestrales.', tags: ['VIP', 'Corporativo'], created_at: new Date().toISOString() },
  { id: 'cli-5', tenant_id: 'demo-tenant', full_name: 'Banco Popular - RRHH', phone: '809-555-0105', email: 'eventos@bancopopular.com.do', address: 'Av. John F. Kennedy, Piantini', notes: 'Eventos corporativos anuales.', tags: ['Corporativo', 'VIP'], created_at: new Date().toISOString() },
  { id: 'cli-6', tenant_id: 'demo-tenant', full_name: 'Pedro Sánchez', phone: '809-555-0106', email: 'pedro@email.com', address: 'Calle Duarte #88', notes: 'Primera vez. Cotizó paquete básico.', tags: ['Nuevo'], created_at: new Date().toISOString() },
]

export const demoServices = [
  { id: 'svc-1', tenant_id: 'demo-tenant', name: 'Payaso Pepito', description: 'Payaso profesional con show de magia, juegos y payasadas.', base_price: 3500, duration_minutes: 120, category: 'Payasos', image_url: null, availability: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab', 'Dom'], is_active: true },
  { id: 'svc-2', tenant_id: 'demo-tenant', name: 'Mago Fantástico', description: 'Show de magia infantil con participación del público.', base_price: 4500, duration_minutes: 90, category: 'Magos', image_url: null, availability: ['Sab', 'Dom'], is_active: true },
  { id: 'svc-3', tenant_id: 'demo-tenant', name: 'Pintacaritas Creativo', description: 'Artista profesional con diseños faciales infantiles.', base_price: 2500, duration_minutes: 120, category: 'Pintacaritas', image_url: null, availability: ['Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab', 'Dom'], is_active: true },
  { id: 'svc-4', tenant_id: 'demo-tenant', name: 'Inflable Castillo', description: 'Castillo inflable de 4x4 metros para niños de 3-10 años.', base_price: 5500, duration_minutes: 240, category: 'Inflables', image_url: null, availability: ['Sab', 'Dom'], is_active: true },
  { id: 'svc-5', tenant_id: 'demo-tenant', name: 'DJ Mini Fiesta', description: 'Música infantil, luces y juegos de baile.', base_price: 4000, duration_minutes: 180, category: 'DJ', image_url: null, availability: ['Vie', 'Sab', 'Dom'], is_active: true },
  { id: 'svc-6', tenant_id: 'demo-tenant', name: 'Animadora Princesa', description: 'Animadora vestida de princesa con juegos y cuentos.', base_price: 3000, duration_minutes: 120, category: 'Animadores', image_url: null, availability: ['Sab', 'Dom'], is_active: true },
]

export const demoPackages = [
  { id: 'pkg-1', tenant_id: 'demo-tenant', name: 'Paquete Básico', description: 'Payaso + Pintacaritas. Ideal para 15-20 niños.', services: ['svc-1', 'svc-3'], discount_percentage: 10, total_price: 5400, is_active: true },
  { id: 'pkg-2', tenant_id: 'demo-tenant', name: 'Paquete Premium', description: 'Todo incluido: Payaso, Mago, Pintacaritas, Inflable y DJ.', services: ['svc-1', 'svc-2', 'svc-3', 'svc-4', 'svc-5'], discount_percentage: 20, total_price: 16400, is_active: true },
  { id: 'pkg-3', tenant_id: 'demo-tenant', name: 'Paquete Escolar', description: 'Payaso + Pintacaritas + Inflable. Ideal para colegios.', services: ['svc-1', 'svc-3', 'svc-4'], discount_percentage: 15, total_price: 10200, is_active: true },
]

export const demoEmployees = [
  { id: 'emp-1', tenant_id: 'demo-tenant', user_id: null, artistic_name: 'Pepito el Payaso', specialties: ['Payaso', 'Animador'], availability: {}, rating: 4.8, documents: {}, payment_type: 'per_event' as const, payment_amount: 2500, is_active: true, users: { full_name: 'Juan Pérez', email: 'juan@clownpro.com', avatar_url: null } },
  { id: 'emp-2', tenant_id: 'demo-tenant', user_id: null, artistic_name: 'Mago Estrella', specialties: ['Mago', 'Animador'], availability: {}, rating: 4.9, documents: {}, payment_type: 'per_event' as const, payment_amount: 3000, is_active: true, users: { full_name: 'Carlos Ruiz', email: 'carlos@clownpro.com', avatar_url: null } },
  { id: 'emp-3', tenant_id: 'demo-tenant', user_id: null, artistic_name: 'Luna Pintacaritas', specialties: ['Pintacaritas'], availability: {}, rating: 4.7, documents: {}, payment_type: 'per_event' as const, payment_amount: 1500, is_active: true, users: { full_name: 'Laura Vásquez', email: 'laura@clownpro.com', avatar_url: null } },
  { id: 'emp-4', tenant_id: 'demo-tenant', user_id: null, artistic_name: 'Princesa Alegría', specialties: ['Animador', 'DJ'], availability: {}, rating: 4.6, documents: {}, payment_type: 'per_event' as const, payment_amount: 2000, is_active: true, users: { full_name: 'Alejandra Santos', email: 'ale@clownpro.com', avatar_url: null } },
]

export const demoTransactions = [
  { id: 'txn-1', tenant_id: 'demo-tenant', event_id: 'evt-1', type: 'income', category: 'Eventos', amount: 3500, payment_method: 'Transferencia', description: 'Abono cumpleaños Sofía', transaction_date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0], created_at: new Date().toISOString(), events: { title: 'Cumpleaños de Sofía' } },
  { id: 'txn-2', tenant_id: 'demo-tenant', event_id: 'evt-2', type: 'income', category: 'Eventos', amount: 5000, payment_method: 'Efectivo', description: 'Abono baby shower Laura', transaction_date: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0], created_at: new Date().toISOString(), events: { title: 'Baby Shower de Laura' } },
  { id: 'txn-3', tenant_id: 'demo-tenant', event_id: 'evt-4', type: 'income', category: 'Eventos', amount: 35000, payment_method: 'Transferencia', description: 'Pago total escuela Arcoíris', transaction_date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0], created_at: new Date().toISOString(), events: { title: 'Día del Niño - Escuela Arcoíris' } },
  { id: 'txn-4', tenant_id: 'demo-tenant', event_id: 'evt-5', type: 'income', category: 'Eventos', amount: 11000, payment_method: 'Cheque', description: 'Abono Banco Popular', transaction_date: new Date().toISOString().split('T')[0], created_at: new Date().toISOString(), events: { title: 'Fiesta Corporativa Banco Popular' } },
  { id: 'txn-5', tenant_id: 'demo-tenant', event_id: null, type: 'expense', category: 'Gasolina', amount: 2500, payment_method: 'Tarjeta', description: 'Gasolina semana 1', transaction_date: new Date(Date.now() - 86400000 * 6).toISOString().split('T')[0], created_at: new Date().toISOString(), events: null },
  { id: 'txn-6', tenant_id: 'demo-tenant', event_id: null, type: 'expense', category: 'Materiales', amount: 1800, payment_method: 'Efectivo', description: 'Globos, serpentinas y confeti', transaction_date: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0], created_at: new Date().toISOString(), events: null },
  { id: 'txn-7', tenant_id: 'demo-tenant', event_id: null, type: 'expense', category: 'Pagos empleados', amount: 9000, payment_method: 'Transferencia', description: 'Pagos del fin de semana', transaction_date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0], created_at: new Date().toISOString(), events: null },
  { id: 'txn-8', tenant_id: 'demo-tenant', event_id: null, type: 'expense', category: 'Alquiler equipo', amount: 3500, payment_method: 'Efectivo', description: 'Alquiler inflable extra grande', transaction_date: new Date(Date.now() - 86400000 * 1).toISOString().split('T')[0], created_at: new Date().toISOString(), events: null },
]

export const demoInventory = [
  { id: 'inv-1', tenant_id: 'demo-tenant', name: 'Pelucas de payaso (set 5)', category: 'Disfraces', description: 'Pelucas de colores variados', quantity: 8, status: 'available', assigned_event_id: null, alert_threshold: 3 },
  { id: 'inv-2', tenant_id: 'demo-tenant', name: 'Pinturas faciales', category: 'Maquillaje', description: 'Set de pinturas hipoalergénicas', quantity: 12, status: 'available', assigned_event_id: null, alert_threshold: 5 },
  { id: 'inv-3', tenant_id: 'demo-tenant', name: 'Inflable Castillo Mediano', category: 'Inflables', description: 'Castillo inflable 3x3m', quantity: 2, status: 'in_use', assigned_event_id: 'evt-4', alert_threshold: 1 },
  { id: 'inv-4', tenant_id: 'demo-tenant', name: 'Bocinas JBL PartyBox', category: 'Equipo sonido', description: 'Sistema de sonido portátil', quantity: 3, status: 'available', assigned_event_id: null, alert_threshold: 1 },
  { id: 'inv-5', tenant_id: 'demo-tenant', name: 'Set de magia infantil', category: 'Props', description: 'Varita, sombrero de conejo, cartas', quantity: 4, status: 'available', assigned_event_id: null, alert_threshold: 2 },
  { id: 'inv-6', tenant_id: 'demo-tenant', name: 'Decoración princesas', category: 'Decoración', description: 'Guirnaldas, mantel, platos desechables', quantity: 15, status: 'available', assigned_event_id: null, alert_threshold: 5 },
  { id: 'inv-7', tenant_id: 'demo-tenant', name: 'Inflable Tobogán', category: 'Inflables', description: 'Tobogán inflable con piscina', quantity: 1, status: 'maintenance', assigned_event_id: null, alert_threshold: 1 },
]
